2024 S1 updates
WEHI-ResearchComputing/student-intern-organiser pull request #71
Opened 2024-05-10 04:25 UTC by junhual1

# Student Organiser Project in 2024 Semester 1

## Introduction
We enhanced the web application by developing a strategic roadmap, introducing a robust batch information import algorithm, and launching a new functional page to improve user accessibility. All the new functionalities and pages, along with the filter method, will be introduced.

## New Pages Added
- **Function Page**: Serve as a centralized hub for administrative actions. 
- **Add Profile Picture**: Allows students to upload or update their profile picture.
- **Empty WEHI Email**: Identifies students with missing or uncorrect email addresses. User can download the generated CSV file and upload CSV file.
- **Github Username**: Identifies students with missing GitHub Username. 
- **New Intake Email ACK**: Manages acknowledgment processes for new intakes.
- **New Intake Quick Review**: Provides a quick review feature for new intakes.
- **Allocation**: Refer to the student project allocation page.

## Filter Definitions for Pages
### Empty WEHI Email
- Intake of students is 'current'
- Status is [10, 11, 12, 13] 
- No WEHI email or have an email in an incorrect format.
### Github Username
- Intake of students is 'current'
- Status is [10, 11, 12, 13]
- No Github Usename
### New Intake Email ACK
- Intake of students is 'new'
- Status is only [ 02 ]
### New Intake Quick Review
- Intake of students is 'new'
- Status is only [ 03 ]

## Testing and Expected Outcomes
We test each functionality to verify it works as expected and document the expected outcomes for each test scenario to facilitate efficient debugging and validation. While we have tested and refined the expected outcomes for major functionalities on each page, some functionalities still require expanded expected outcomes.

Link to Regression Test File :
https://wehieduau.sharepoint.com/:x:/s/StudentInternGroupatWEHI/ERTFF_vw-kREgvjukplnjv4BPy78XyMtaADKwjD540iPSQ?e=sxbGqK

## Issues and Contributions
All issues are tracked on our GitHub page. Please visit https://github.com/WEHI-ResearchComputing/student-intern-organiser/issues to report issues or contribute to the project.

## How to Use
For a detailed guide on how to use the application, refer to Rowland's instructional video at https://wehieduau.sharepoint.com/sites/StudentInternGroupatWEHI/_layouts/15/stream.aspx?id=%2Fsites%2FStudentInternGroupatWEHI%2FShared%20Documents%2FStudent%20Organiser%2FONBOARDING%20%5BMUST%20READ%5D%2FDocument%20Student%20Onboarding%20Process%20using%20Student%20Organiser%20and%20REDCap%2D20231205%5F140823%2DMeeting%20Recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E9d4a93bf%2D37eb%2D478a%2Db7a8%2D7b37c85d4e4b.

2024-05-10 22:13 UTC, rowlandm requested changes
Looks pretty good - still needs a small amount of work.

2024-05-10 22:13 UTC, rowlandm commented on .gitignore
Should be .idea/ to ignore all the .xml files...

2024-05-10 22:13 UTC, rowlandm commented on .idea/vcs.xml
All these .xml files are not needed I assume.

2024-05-10 22:13 UTC, rowlandm commented on app.py
> +##----------- 2024 S1 New Code----------------##
Really doesn't help much. Can remove

2024-05-10 22:13 UTC, rowlandm commented on app.py
> +    # query = '''
Remove commented code - don't leave commented code in any code :)

2024-05-10 22:13 UTC, rowlandm commented on templates/2024Github.html
Please rename all 2024 files as this will confuse over time.

eg. github.html

2024-05-10 22:13 UTC, rowlandm commented on templates/2024Github.html
> +                var selectedRows = $('.studentCheckbox:checked').each(function() {
Not working - copy WEHI email doesn't work and neither does COpy Personal.

I don't see how personal would ever work given there is no email for personal....

2024-05-10 22:13 UTC, rowlandm commented on templates/2024Github.html
> +                if (emails.length > 0) {
Why do we need acknowledgement email script for github?

2024-05-10 22:13 UTC, rowlandm commented on templates/2024Update_Wehi.html
Please rename all 2024 files as this will confuse over time.

eg. update_wehi_emails.html

This filename is more clear.

2024-05-10 22:13 UTC, rowlandm commented on templates/2024current_student.html
as per other 2024 files.

2024-05-10 22:13 UTC, rowlandm commented on templates/2024error.html
as per other 2024 files.

2024-05-10 22:13 UTC, rowlandm commented on templates/2024menu_page.html
as per other 2024 files.

2024-05-10 22:14 UTC, rowlandm commented
Also please remove other branches that look similar - I ended testing on S12024Final that wasn't final.

2024-05-11 04:23 UTC, junhual1 commented
We will be looking into it!

2024-05-14 03:43 UTC, closed without merging